name: Continuous Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @siegrift/cypress-trusted-types
        uses: actions/checkout@v2
      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1

  lint-compile:
    runs-on: ubuntu-latest
    name: Lint and compile
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Compile
        run: yarn build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 16.x]
        browser: [chrome, firefox]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Checkout
        uses: actions/checkout@v2
        # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn test:start-server
          browser: ${{ matrix.browser }}

  required-checks-passed:
    name: All required checks passed
    runs-on: ubuntu-latest
    needs: [lint-compile, test]
    steps:
      - run: exit 0
